# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '5000:80' # 로컬 포트 5000을 컨테이너의 80 포트에 매핑
    networks:
      - webapp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '8081:8081' # 로컬 포트 8081을 컨테이너의 8081 포트에 매핑
    networks:
      - webapp

networks:
  webapp:
    driver: bridge
